name: DevSecOps Cloud Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. SAST Scan (Bandit)
        run: |
          pip install bandit
          # -r .: quét toàn bộ thư mục
          # -v: hiển thị chi tiết lỗi trong Log
          bandit -r . -v

      - name: 3. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest

      - name: 5. Webhook Gateway (Deploy to Render)
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: 6. DAST Scan (OWASP ZAP)
        if: success()
        run: |
          sleep 30
          docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://mmtnc-app.onrender.com