name: DevSecOps Cloud Pipeline

on:
  push:
    branches: [ "main" ] # Tự động chạy khi bạn push code lên GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. SAST Scan (Bandit)
        run: |
          pip install bandit
          bandit -r . -f txt -o report_sast.txt || true

      - name: 3. Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest