name: DevSecOps Cloud Pipeline

on:
  push:
    branches: [ "main" ] # Tự động chạy khi bạn push code lên GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4 # Đã cập nhật phiên bản mới nhất

      - name: 2. SAST Scan (Bandit)
        run: |
          pip install bandit
          # Quét lỗi bảo mật và xuất báo cáo
          bandit -r . -f txt -o report_sast.txt || true 

      - name: 3. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Build and Push Docker Image
        run: |
          # Build image với tag là latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest .
          # Đẩy image lên Docker Hub (Sửa lỗi thụt lề ở đây)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmtnc-app:latest

      # - name: 5. Webhook Gateway (Deploy to Render)
      #   if: success()
      #   run: |
      #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}